spring:
  datasource:
    url: jdbc:postgresql://localhost:30074/devdb
    username: pguser
    password: pgpass123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  data:
    mongodb:
      uri: mongodb://root:admin123@localhost:30084
      database: usersdb
